apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001